name: CI/CD
on:
  push:
    tags:
      - 'v*'
  pull_request:
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    needs: clippy_check
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
  valgrind_test:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4
      - name: Install valgrind
        run: sudo apt-get install -y valgrind
      - name: Install cargo-valgrind
        run: cargo install cargo-valgrind
      - name: Run Valgrind tests
        run: cargo valgrind test --verbose
  publish:
    runs-on: ubuntu-latest
    needs: valgrind_test
    if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run publish-action
        uses: tu6ge/publish-action@v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
